- hosts: localhost
  tasks:
    - name: Install essentials
      become: yes
      package: name={{item}} state=present
      with_items:
        - dconf-editor
        - redhat-text-fonts
        - redhat-display-fonts
        - mozilla-fira-mono-fonts
        - mozilla-fira-sans-fonts
    - name: Install dev
      become: yes
      package: name={{item}} state=present
      with_items:
        - emacs
        - golang
        - make
        - automake
        - gcc
        - gcc-c++
    - name: Install media
      become: yes
      package: name={{item}} state=present
      with_items:
        - mpv
    - name: Install containers stuff
      become: yes
      package: name={{item}} state=present
      with_items:
        - origin-clients
        - podman
        - buildah
        - skopeo
    - name: Install syncthing
      become: yes
      package: name={{item}} state=present
      with_items:
        - syncthing
        - syncthing-gtk
    - name: Install virtualization packages
      become: yes
      package: name={{item}} state=present
      with_items:
        - virt-manager
        - qemu-kvm
        - qemu-img
        - virt-install
        - bridge-utils
        - libvirt
        - libvirt-devel
        - libvirt-daemon-kvm
