keys:
  - &vincent 8C4E8DDA04C18C6B503BD2DBB7E7CF1C634256FA
  - &aomi b14ab1e44008e7d4c39875324d5981054462545d
  - &wakasu 3f65577842cabda3955d1f5603286b3ea9ac52bb
  - &sakhalin 8b80ab02638ab9c34f6c21bd69928b5908e10cbf
  - &kerkouane b8b02c0885a74753f8fb53f031f0386f20f3e4ec
creation_rules:
  # - path_regex: secrets/admins/[^/]+\.yaml$
  #   key_groups:
  #   - pgp:
  #     - *joerg
  # - path_regex: eve/secrets/[^/]+\.yaml$
  #   key_groups:
  #   - pgp:
  #     - *joerg
  #     - *eve
  # - path_regex: eva/secrets/[^/]+\.yaml$
  #   key_groups:
  #   - pgp:
  #     - *joerg
  #     - *eva
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *aomi
      - *wakasu
      - *sakhalin
      - *kerkouane
