keys:
  - &vincent 8C4E8DDA04C18C6B503BD2DBB7E7CF1C634256FA
  - &aomi b14ab1e44008e7d4c39875324d5981054462545d
  - &wakasu 3f65577842cabda3955d1f5603286b3ea9ac52bb
  - &sakhalin 8b80ab02638ab9c34f6c21bd69928b5908e10cbf
  - &kerkouane b8b02c0885a74753f8fb53f031f0386f20f3e4ec
  - &naruhodo 5722867ac621fd15d2dfc7eab7bfec55a117c1bf
  - &k8sn1 298092af3b4de6f5a6cb51a14f2247aa4fa91e04
  - &k8sn2 0ebe388f6827fe2eace1055d0b23ac2723c1de53
  - &k8sn3 95233a9c933a7ff9d7a6ca9a531bfac356b8f712
creation_rules:
  - path_regex: secrets/wakasu/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *wakasu
  - path_regex: secrets/aomi/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *aomi
  - path_regex: secrets/sakhalin/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *sakhalin
  - path_regex: secrets/kerkouane/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *kerkouane
  - path_regex: secrets/naruhodo/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *naruhodo
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *vincent
      - *aomi
      - *wakasu
      - *sakhalin
      - *kerkouane
      - *naruhodo
      - *k8sn1
      - *k8sn2
      - *k8sn3
