---
- hosts: localhost
  roles:
  - common
  - desktop
  - { role: laptop, when: ansible_form_factor == 'Notebook' }

# ansible_hostname == 'hokkaido'
# ansible_product_version == 'ThinkPad X220'
# ansible_form_factor == 'Notebook'