---
- name: Install dconf-editor
  become: yes
  package: name=dconf-editor state=present
- name: Enable Night Light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present
- name: Enable Night Light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "true"
    state: present
- name: Enable Night Light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "5000"
    state: present