image: fedora/latest
secrets:
  - 67527e1f-d69c-4f8e-a26d-21685f4ed380
sources:
  - git@git.sr.ht:~vdemeester/secrets
tasks:
- setup: |
    dnf install -y tar gzip
- install_nix: |
    set -euo pipefail
    curl -L https://nixos.org/nix/install | sh
- install_home_manager: |
    nix-shell $(nix eval --raw '(import ./home/nix/sources.nix).["home-manager"].outPath') -A install
triggers:
- action: email
  condition: failure
  to: vincent@sbr.pm
