image: fedora/latest
tasks:
- setup: |
    sudo dnf install -y tar jq
- install_nix: |
    set -euo pipefail
    curl -L https://nixos.org/nix/install | sh
- install_home_manager: |
    . /home/build/.nix-profile/etc/profile.d/nix.sh
    nix-shell $(jq --raw-output '.["home-manager"].url' ./home/nix/sources.json) -A install
triggers:
- action: email
  condition: failure
  to: vincent@sbr.pm
