image: nixos/20.03
secrets:
  - 0818d60d-b587-4d4e-81d8-dc15072ccb97
tasks:
- setup: |
    nix-env -iA cachix -f https://cachix.org/api/v1/install
    cachix use shortbrain
- systems: |
    set -euo pipefail
    set +x
    export CACHIX_SIGNING_KEY=$(cat ~/.cachix.key)
    set -x
    nix-build home -A wakasu -A hokkaido
triggers:
- action: email
  condition: failure
  to: vincent@sbr.pm
