[networks.vpn]
v4 = "10.100.0.0" #/24

[hosts.naruhodo]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7zGAceSiqFtWHwt7HVjN24SCyWCC26l6YrgUP/qtPc vincent@naruhodo" }

[hosts.naruhodo.wireguard]
pubkey = "XXyyJ9GlIiZnUm+Bkpz+NSrFiosjfY4FB2PgLXVPLkI="
addrs = { v4 = "10.100.0.15" }

[hosts.aomi]
network = "vpn"
ssh = { pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJ3QqVCUiE4BIFKTJLN6mSnp9bLSnJ3gE8ScbAajGsH vincent@aomi" }
addrs = { v4 = "192.168.1.23" }

[hosts.aomi.wireguard]
pubkey = "XT4D9YLeVHwMb9R4mhBLSWHYF8iBO"
addrs = { v4 = "10.100.0.17" }

[hosts.kerkouane]
network = "vpn"
addrs = { v4 = "167.99.17.238" } # FIXME probably not right

[hosts.kerkounae.wireguard]
addrs = { v4 = "10.100.0.1" }
port = 51820